
apiVersion: v1
kind: Pod
metadata:
  name: ns-endpoint-1
spec:
  containers:
  - image: networkservicemesh/vppagent-forwarder:master
    name: ns-endpoint-1
    volumeMounts:
    - mountPath: /tmp
      name: ns-endpoint-1-volume
  nodeName: <give node name>
  volumes:
  - name: ns-endpoint-1-volume
    hostPath:
      # directory location on host
      path: /tmp
      # this field is optional
      # type: Director
